# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bettor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='title',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='wager',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='winner',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='bet',
            name='bettor',
            field=models.OneToOneField(help_text='Enter who made the bet', null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Bettor'),
        ),
        migrations.AddField(
            model_name='bet',
            name='taker',
            field=models.OneToOneField(help_text='Enter who accepted the bet', null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Taker'),
        ),
    ]
