# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20171111_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='winner',
            new_name='won',
        ),
        migrations.AlterField(
            model_name='bet',
            name='bettor',
            field=models.ForeignKey(help_text='Enter who made the bet', null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Bettor'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='taker',
            field=models.ForeignKey(help_text='Enter who accepted the bet', null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Taker'),
        ),
    ]
